import React from "react";
import type { World } from "../../engine/types";
import { ACHIEVEMENTS, achievementProgress, legacyScore, OUTCOMES, scenarioProgress, SCENARIOS } from "../../engine/gameplay";
import { C } from "../theme";

export function LegacyView({ world }: { world: World }) {
  const scenario = SCENARIOS[world.gameplay.scenarioId];
  const objectives = scenarioProgress(world);
  const unlocked = new Set(world.gameplay.achievements.map((a) => a.id));
  const reachedOutcomes = new Set(world.gameplay.outcomes.map((o) => o.id));
  const score = legacyScore(world);
  const completion = ACHIEVEMENTS.length ? unlocked.size / ACHIEVEMENTS.length : 0;
  return <div className="be-legacy"><LegacyStyles />
    <section className="legacy-cabinet-hero"><div className="legacy-cabinet-hero__copy"><div className="legacy-kicker">Trophy cabinet · Run #{String(world.gameplay.runSeed ?? 0).padStart(9, "0").slice(-9)}</div><h2>{scenario.icon} {scenario.name}</h2><p>{scenario.pitch} Each seeded company creates a different story of decisions, shocks and opportunities.</p><div className="legacy-hero-progress"><i style={{ width: `${completion * 100}%` }} /></div><small>{unlocked.size} of {ACHIEVEMENTS.length} achievements displayed</small></div><div className="legacy-score-medal" aria-label={`Legacy score ${score.toLocaleString()}`}><span>★</span><small>LEGACY SCORE</small><b>{score.toLocaleString()}</b></div></section>
    <SectionHead number="01" title="Scenario assignment" text="Complete the brief and build toward a stronger result." />
    <div className="scenario-card-grid">{objectives.map((objective, index) => <article key={objective.label} className={objective.done ? "done" : ""}><div className="scenario-check">{objective.done ? "✓" : index + 1}</div><div><b>{objective.label}</b><p>{objective.detail}</p><span>{objective.done ? "COMPLETED" : "IN PROGRESS"}</span></div></article>)}</div>
    <SectionHead number="02" title="Achievement gallery" text="Milestones earned across this company run." />
    <div className="trophy-grid">{ACHIEVEMENTS.map((achievement) => { const done = unlocked.has(achievement.id); const progress = Math.max(0, Math.min(1, achievementProgress(world, achievement.id))); return <article key={achievement.id} className={done ? "unlocked" : "locked"}><div className="trophy-shelf"><span>{done ? achievement.icon : "✦"}</span></div><div className="trophy-copy"><div className="trophy-title"><b>{achievement.name}</b>{done && <em>UNLOCKED</em>}</div><p>{achievement.desc}</p><div className="trophy-progress"><i style={{ width: `${progress * 100}%` }} /></div><small>{done ? "Complete" : `${Math.round(progress * 100)}% progress`}</small></div></article>; })}</div>
    <SectionHead number="03" title="Chapter outcomes" text="Major endings unlock a new chapter—the company always continues." />
    <div className="legacy-outcome-grid">{OUTCOMES.map((outcome) => { const reached = reachedOutcomes.has(outcome.id); return <article key={outcome.id} className={reached ? "reached" : ""}><span className="outcome-icon">{outcome.icon}</span><div><div className="outcome-title"><b>{outcome.name}</b>{reached && <em>REACHED</em>}</div><p>{outcome.desc}</p></div></article>; })}</div>
    <SectionHead number="04" title="Decision scrapbook" text="The calls that shaped this particular company." />
    {!world.gameplay.decisionHistory.length ? <div className="legacy-empty"><span>📝</span><div><b>Your first defining choice is still ahead</b><p>Event decisions and their later consequences will be preserved here.</p></div></div> : <div className="decision-scrapbook">{world.gameplay.decisionHistory.map((entry, index) => <article key={`${entry.eventId}_${entry.resolvedTick}`}><div className="decision-day"><small>DAY</small><b>{entry.resolvedTick}</b></div><div className="decision-copy"><small>DECISION {String(index + 1).padStart(2, "0")}</small><h4>{entry.title}</h4><strong>→ {entry.choiceLabel}</strong><p>{entry.immediateText}</p>{entry.delayedText && <div className="decision-consequence"><span>Later consequence</span>{entry.delayedText}</div>}</div></article>)}</div>}
  </div>;
}

function SectionHead({ number, title, text }: { number: string; title: string; text: string }) { return <div className="legacy-section-head"><div><span>{number}</span><h3>{title}</h3></div><p>{text}</p></div>; }

function LegacyStyles() { return <style>{`
  .be-legacy{color:${C.ink};padding-bottom:30px}.legacy-cabinet-hero{position:relative;overflow:hidden;min-height:210px;border-radius:24px;padding:26px;display:flex;align-items:center;justify-content:space-between;gap:24px;color:white;background:radial-gradient(circle at 80% 10%,rgba(120,217,255,.45),transparent 28%),linear-gradient(125deg,#10245a,#174f9f 57%,#5735a4);box-shadow:0 17px 40px rgba(18,48,105,.24)}.legacy-cabinet-hero:after{content:"";position:absolute;right:6%;bottom:-45px;width:260px;height:90px;border-radius:50%;background:rgba(255,255,255,.12);filter:blur(4px)}.legacy-cabinet-hero__copy{position:relative;z-index:2;max-width:720px}.legacy-kicker{font-size:12px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:#bfe7ff}.legacy-cabinet-hero h2{font-size:clamp(25px,3.2vw,39px);line-height:1.08;color:white;margin:7px 0 9px}.legacy-cabinet-hero p{font-size:14px;line-height:1.55;color:#e5efff;margin:0;max-width:670px}.legacy-cabinet-hero__copy>small{display:block;font-size:11px;color:#d5e7ff;margin-top:7px}.legacy-hero-progress{width:min(430px,100%);height:9px;border-radius:99px;background:rgba(255,255,255,.17);overflow:hidden;margin-top:17px;border:1px solid rgba(255,255,255,.2)}.legacy-hero-progress i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#55dc91,#ffd55a);box-shadow:0 0 13px rgba(255,213,90,.5)}
  .legacy-score-medal{position:relative;z-index:2;width:150px;height:150px;border-radius:50%;flex:0 0 150px;display:flex;flex-direction:column;align-items:center;justify-content:center;background:linear-gradient(145deg,#fff3a9,#e9a624);border:6px solid rgba(255,255,255,.55);box-shadow:0 12px 29px rgba(30,22,78,.3),inset 0 0 0 2px rgba(147,88,0,.2);color:#674007}.legacy-score-medal>span{font-size:24px;line-height:1}.legacy-score-medal small{font-size:9px;font-weight:950;letter-spacing:.1em;margin-top:3px}.legacy-score-medal b{font-size:24px;margin-top:2px}.legacy-section-head{display:flex;align-items:end;justify-content:space-between;gap:16px;margin:26px 3px 11px}.legacy-section-head>div{display:flex;align-items:center;gap:10px}.legacy-section-head>div>span{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:#e7efff;color:#275da9;font-size:11px;font-weight:950}.legacy-section-head h3{font-size:19px;margin:0}.legacy-section-head p{font-size:12px;color:${C.faint};margin:0;text-align:right}
  .scenario-card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:11px}.scenario-card-grid article{display:grid;grid-template-columns:46px 1fr;gap:11px;min-height:110px;padding:14px;border:1px solid ${C.line};border-radius:16px;background:${C.panel};box-shadow:0 4px 13px rgba(28,51,94,.06);transition:.16s ease}.scenario-card-grid article:hover{transform:translateY(-2px);border-color:#aec8f5;box-shadow:0 9px 20px rgba(26,70,140,.12)}.scenario-card-grid article.done{border-color:#97ddb8;background:linear-gradient(145deg,#f1fff7,#fff)}.scenario-check{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:#e8effb;color:#42628f;font-size:16px;font-weight:950}.scenario-card-grid .done .scenario-check{background:linear-gradient(145deg,#37c978,#159d5a);color:white}.scenario-card-grid b{font-size:14px}.scenario-card-grid p{font-size:12.5px;line-height:1.45;color:${C.dim};margin:4px 0 9px}.scenario-card-grid article span{font-size:9px;font-weight:950;letter-spacing:.08em;color:#6b7f9f}.scenario-card-grid article.done span{color:${C.green}}
  .trophy-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:11px}.trophy-grid article{display:grid;grid-template-columns:72px 1fr;gap:13px;min-height:128px;padding:15px;border:1px solid ${C.line};border-radius:17px;background:linear-gradient(145deg,#fff,#f8faff);box-shadow:0 4px 13px rgba(33,55,96,.06);transition:.17s ease}.trophy-grid article:hover{transform:translateY(-2px);box-shadow:0 9px 22px rgba(28,68,136,.12)}.trophy-grid article.locked{filter:saturate(.55)}.trophy-grid article.unlocked{border-color:#f0ce68;background:linear-gradient(145deg,#fffdf3,#fff)}.trophy-shelf{width:70px;height:86px;display:grid;place-items:center;border-radius:35px 35px 15px 15px;background:linear-gradient(160deg,#e8eef9,#cad8ed);box-shadow:inset 0 -8px 0 rgba(84,105,144,.12)}.unlocked .trophy-shelf{background:radial-gradient(circle at 35% 25%,#fff6ba,#f4bf3e 60%,#cb7d12);box-shadow:0 8px 18px rgba(197,132,20,.22),inset 0 -8px 0 rgba(150,86,0,.12)}.trophy-shelf span{font-size:34px}.trophy-title,.outcome-title{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.trophy-title b,.outcome-title b{font-size:14px}.trophy-title em,.outcome-title em{font-size:8.5px;font-style:normal;font-weight:950;letter-spacing:.07em;padding:3px 6px;border-radius:999px;background:#fff0ad;color:#7c4b06;border:1px solid #efc954}.trophy-copy p{font-size:12px;color:${C.dim};line-height:1.4;margin:5px 0 10px}.trophy-progress{height:8px;border-radius:99px;background:#e6ecf6;overflow:hidden}.trophy-progress i{height:100%;display:block;border-radius:inherit;background:linear-gradient(90deg,#277bee,#7554e8)}.unlocked .trophy-progress i{background:linear-gradient(90deg,#f1a91e,#ffd55e)}.trophy-copy>small{display:block;color:${C.faint};font-size:10px;margin-top:4px}
  .legacy-outcome-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:11px}.legacy-outcome-grid article{display:grid;grid-template-columns:54px 1fr;gap:12px;padding:15px;border-radius:17px;background:${C.panel};border:1px solid ${C.line};box-shadow:0 4px 12px rgba(31,53,91,.05)}.legacy-outcome-grid article.reached{border-color:#bba9f2;background:linear-gradient(145deg,#f6f2ff,#fff)}.outcome-icon{width:52px;height:52px;border-radius:15px;display:grid;place-items:center;font-size:27px;background:#eaf0fb}.reached .outcome-icon{background:linear-gradient(145deg,#d9caff,#8769e9)}.outcome-title em{background:#e9ddff;border-color:#c7b2f3;color:#5433a1}.legacy-outcome-grid p{font-size:12.5px;line-height:1.45;color:${C.dim};margin:5px 0 0}
  .legacy-empty{display:flex;gap:13px;align-items:center;padding:18px;border:2px dashed #c9d6ea;border-radius:17px;background:#f8fbff}.legacy-empty>span{font-size:29px}.legacy-empty b{font-size:14px}.legacy-empty p{font-size:12.5px;color:${C.dim};margin:4px 0 0}.decision-scrapbook{display:grid;gap:11px}.decision-scrapbook article{display:grid;grid-template-columns:74px 1fr;border:1px solid ${C.line};border-radius:18px;background:${C.panel};overflow:hidden;box-shadow:0 5px 15px rgba(27,53,99,.07)}.decision-day{display:flex;flex-direction:column;align-items:center;justify-content:center;background:linear-gradient(145deg,#1c4d9d,#653fae);color:white;min-height:150px}.decision-day small{font-size:9px;letter-spacing:.12em;color:#cfe3ff}.decision-day b{font-size:22px;margin-top:2px}.decision-copy{padding:16px}.decision-copy>small{font-size:9px;color:${C.faint};font-weight:900;letter-spacing:.11em}.decision-copy h4{font-size:15px;margin:4px 0}.decision-copy strong{font-size:12px;color:${C.violet}}.decision-copy>p{font-size:12.5px;line-height:1.5;color:${C.dim};margin:7px 0 0}.decision-consequence{margin-top:10px;padding:9px 11px;border-left:4px solid #efa92d;border-radius:8px;background:#fff8e8;color:#654518;font-size:12px;line-height:1.4}.decision-consequence span{display:block;font-size:9px;font-weight:950;text-transform:uppercase;letter-spacing:.07em;color:#a46709;margin-bottom:2px}
  .be-legacy .scenario-card-grid article span,.be-legacy .trophy-title em,.be-legacy .outcome-title em,.be-legacy .decision-day small,.be-legacy .decision-copy>small,.be-legacy .decision-consequence span{font-size:10.5px}.be-legacy .trophy-copy>small{font-size:11px}
  @media(max-width:720px){.legacy-cabinet-hero{padding:20px 17px;align-items:flex-start;min-height:0}.legacy-score-medal{width:105px;height:105px;flex-basis:105px;border-width:4px}.legacy-score-medal>span{font-size:17px}.legacy-score-medal small{font-size:9px}.legacy-score-medal b{font-size:17px}.legacy-section-head{align-items:flex-start;flex-direction:column;gap:5px}.legacy-section-head p{text-align:left;padding-left:44px}.trophy-grid,.scenario-card-grid,.legacy-outcome-grid{grid-template-columns:1fr}}@media(max-width:500px){.legacy-cabinet-hero{display:block}.legacy-score-medal{position:absolute;right:13px;top:13px;opacity:.2}.trophy-grid article{grid-template-columns:62px 1fr}.trophy-shelf{width:60px;height:76px}.decision-scrapbook article{grid-template-columns:58px 1fr}.decision-copy{padding:13px}.decision-day b{font-size:18px}}@media(prefers-reduced-motion:reduce){.scenario-card-grid article,.trophy-grid article{transition:none}}
`}</style>; }
